-- [V] Sequence : 순차번호 생성기. 대부분 인위적인 PK 사용용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH   1 -- 1부터 시작(기본값 1)
    INCREMENT BY 1 -- 1씩 증가 ( 기본값 1)
    MAXVALUE     9999 -- 최대값
    MINVALUE     1    -- 최소값
    NOCYCLE  -- CYCLE : 순차번호 9999->1
    NOCACHE;  --
    
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL;
SELECT FRIEND_SEQ.CURRVAL FROM DUAL;
    
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NO NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(20) UNIQUE,
    ADDRESS VARCHAR2(250),
    LAST_MODIFY DATE DEFAULT SYSDATE
);    
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 99999
    NOCACHE NOCYCLE;
SELECT * FROM FRIEND;

INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', '010-9999-9999','서울');
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '유길동', NULL,'서울');
SELECT * FROM FRIEND;    


    
------------ ※ 연습문제  ------------
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;
DROP SEQUENCE MEMBER_SQ;

CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(3),
    LEVELNAME VARCHAR2(20) NOT NULL,
    PRIMARY KEY(LEVELNO)
);
INSERT INTO MEMBER_LEVEL VALUES( -1, 'BLACK');
INSERT INTO MEMBER_LEVEL VALUES( 0, '일반');
INSERT INTO MEMBER_LEVEL VALUES( 1, '실버');
INSERT INTO MEMBER_LEVEL VALUES( 2, '골드');

SELECT * FROM MEMBER_LEVEL;
DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    NO NUMBER(4),
    NAME VARCHAR2(20) NOT NULL,
    PW VARCHAR2(20),
    MAIL VARCHAR2(60),
    POINT NUMBER(10),
    RDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(5),
        PRIMARY KEY(NO),
        CHECK(LENGTH(PW) BETWEEN 1 AND 8),
        UNIQUE(MAIL),
        CHECK(POINT>=0),
        FOREIGN KEY(LEVELNO) REFERENCES MEMBER_LEVEL(LEVELNO)
);

INSERT INTO MEMBER 
    VALUES (MEMBER_SQ.NEXTVAL, '홍길동', 'AA', 'HONG@HONG.COM', 0, TO_DATE('24/09/26', 'YY/MM/DD'), 0);
INSERT INTO MEMBER 
    VALUES (MEMBER_SQ.NEXTVAL, '신길동', 'BB', 'SIN@SIN.COM', 1000, TO_DATE('22/04/01', 'YY/MM/DD'), 1);

SELECT * FROM MEMBER;

CREATE SEQUENCE MEMBER_SQ;
CREATE SEQUENCE MEMBER_SQ
    START WITH   1
    MAXVALUE 9999
    NOCACHE NOCYCLE;
DROP SEQUENCE MEMBER_SQ;
    
SELECT * FROM FRIEND;

SELECT NO, NAME, TO_CHAR(RDATE, 'YYYY/MM/DD'), MAIL, POINT, LEVELNAME ||'고객' LEVELNAME
    FROM MEMBER M, MEMBER_LEVEL L
    WHERE M.LEVELNO=L.LEVELNO;


-- INSERT INTO MEMBER_LEVEL ~
-- INSERT INTO MEMBER ~
-- 연습문제와 같이 출력되도록 SELECT (EQUI JOIN)    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    